const $=id=>document.getElementById(id),c=$('c'),x=c.getContext('2d');let chars=[],bg=null,playing=false,raf=0,start=0,duration=20;const GAP=.08;
function fit(){const [a,b]=$('aspect').value.split(':').map(Number);c.width=960;c.height=Math.round(960*b/a);draw(0)}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function load(file){return new Promise(resolve=>{const im=new Image;im.onload=()=>resolve(im);im.src=URL.createObjectURL(file)})}
function alphaBox(im){const q=document.createElement('canvas'),w=Math.min(im.naturalWidth,600),h=Math.min(im.naturalHeight,600);q.width=w;q.height=h;const z=q.getContext('2d');z.drawImage(im,0,0,w,h);const d=z.getImageData(0,0,w,h).data;let X=w,Y=h,R=-1,B=-1;for(let yy=0;yy<h;yy++)for(let xx=0;xx<w;xx++)if(d[(yy*w+xx)*4+3]>10){X=Math.min(X,xx);Y=Math.min(Y,yy);R=Math.max(R,xx);B=Math.max(B,yy)}return R<0?{x:0,y:0,w,h}:{x:X,y:Y,w:R-X+1,h:B-Y+1}}
function add(file){load(file).then(im=>{chars.push({img:im,name:'Character '+(chars.length+1),height:180,box:alphaBox(im)});render();draw(0);$('msg').textContent=chars.length+' character'+(chars.length>1?'s':'')+' added.'})}
$('add').onclick=()=>{const i=document.createElement('input');i.type='file';i.accept='image/*';i.onchange=()=>i.files[0]&&add(i.files[0]);i.click()}
function render(){const box=$('list'),tl=$('timeline');box.innerHTML='';tl.innerHTML='';chars.forEach((ch,i)=>{const d=document.createElement('div');d.className='char';d.innerHTML='<img src="'+ch.img.src+'"><div><input data-i="'+i+'" data-k="name" value="'+esc(ch.name)+'"><input class="height" data-i="'+i+'" data-k="height" type="number" min="1" step="1" value="'+ch.height+'" placeholder="Height"><label class="upload">Replace image<input data-i="'+i+'" data-k="file" type="file" accept="image/*" hidden></label></div><button data-del="'+i+'">×</button>';box.appendChild(d);const card=document.createElement('div');card.className='card';card.draggable=true;card.dataset.i=i;card.innerHTML='<img src="'+ch.img.src+'"><strong>'+esc(ch.name)+'</strong><small>'+ch.height+' cm</small>';tl.appendChild(card)});
box.querySelectorAll('[data-k=name],[data-k=height]').forEach(e=>e.oninput=()=>{chars[+e.dataset.i][e.dataset.k]=e.dataset.k==='height'?Math.max(1,+e.value||1):e.value;render();draw(0)});box.querySelectorAll('[data-k=file]').forEach(e=>e.onchange=()=>e.files[0]&&load(e.files[0]).then(im=>{chars[+e.dataset.i].img=im;chars[+e.dataset.i].box=alphaBox(im);render();draw(0)}));box.querySelectorAll('[data-del]').forEach(e=>e.onclick=()=>{chars.splice(+e.dataset.del,1);render();draw(0)});let drag=null;tl.querySelectorAll('.card').forEach(card=>{card.ondragstart=()=>{drag=+card.dataset.i;card.classList.add('drag')};card.ondragend=()=>card.classList.remove('drag');card.ondragover=e=>e.preventDefault();card.ondrop=e=>{e.preventDefault();const to=+card.dataset.i;if(drag===null||drag===to)return;const q=chars.splice(drag,1)[0];chars.splice(to,0,q);drag=null;render();draw(0)}})}
function maxHeight(){return chars.reduce((m,ch)=>Math.max(m,ch.height),1)}
function camera(t){if(!chars.length)return{x:.5,scale:1,index:-1};const mode=$('mode').value,n=chars.length;const phase=t/duration;let pos;if(mode==='all')return{x:.5,scale:1,index:-1};const idx=Math.min(n-1,Math.floor(phase*n));const local=(phase*n)%1;const next=Math.min(n-1,idx+1);const p=local<.72?local/.72:1;const a=idx,b=next;const xa=.08+a*(.84/Math.max(1,n-1)),xb=.08+b*(.84/Math.max(1,n-1));const xPos=n===1?.5:xa+(xb-xa)*(local<.72?ease(p):0);const h=chars[idx].height*(local<.72?1:1);const largest=maxHeight();const target=$('mode').value==='zoom'?Math.max(.35,Math.min(1.8,largest/h)):(.78+0.22*(largest/h));return{x:xPos,scale:target,index:idx}}
function ease(v){return v<.5?2*v*v:1-Math.pow(-2*v+2,2)/2}
function draw(t){const W=c.width,H=c.height;x.clearRect(0,0,W,H);x.fillStyle='#dce2e8';x.fillRect(0,0,W,H);if(bg)x.drawImage(bg,0,0,W,H);else{let g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,'#eef1f4');g.addColorStop(1,'#b9c1ca');x.fillStyle=g;x.fillRect(0,0,W,H)}const ground=H*.82;x.strokeStyle='#8994a1';x.lineWidth=2;x.beginPath();x.moveTo(0,ground);x.lineTo(W,ground);x.stroke();if($('grid').checked){x.strokeStyle='rgba(80,95,110,.16)';x.lineWidth=1;for(let i=0;i<=20;i++){const xx=i*W/20;x.beginPath();x.moveTo(xx,ground);x.lineTo(W/2+(xx-W/2)*.35,H*.62);x.stroke()}for(let i=0;i<8;i++){const yy=ground-i*H*.07;x.beginPath();x.moveTo(0,yy);x.lineTo(W,yy);x.stroke()}}if(!chars.length)return;const largest=maxHeight(),baseScale=H*.68/largest,cam=camera(t);chars.forEach((ch,i)=>{const rel=ch.height/largest;const natural=ch.box.h||ch.img.naturalHeight;const scale=baseScale*(ch.height/natural);const worldX=.06+i*(.88/Math.max(1,chars.length-1));let sx=(worldX-cam.x)*W*cam.scale+W/2,sy=ground;const alpha=cam.index>=0&&i!==cam.index&&$('mode').value!=='all'?.72:1;x.save();x.globalAlpha=alpha;const h=ch.img.naturalHeight*scale*cam.scale,w=ch.img.naturalWidth*scale*cam.scale;x.drawImage(ch.img,sx-w/2,sy-h*.9,w,h);if($('labels').checked){x.textAlign='center';x.fillStyle='#182333';x.font='700 '+Math.max(12,W*.014)+'px system-ui';x.fillText(ch.name,sx,ground+22*cam.scale);x.font='500 '+Math.max(10,W*.011)+'px system-ui';x.fillStyle='#4e5d70';x.fillText(ch.height+' cm',sx,ground+39*cam.scale)}x.restore()});$('clock').textContent='00:'+String(Math.floor(t)).padStart(2,'0')+' / 00:'+String(duration).padStart(2,'0')}
function update(){duration=+$('duration').value;$('durText').textContent=duration+'s';draw(0)}
$('duration').oninput=update;$('aspect').onchange=fit;$('mode').onchange=()=>draw(0);
$('play').onclick=()=>{if(playing)return;playing=true;start=performance.now();raf=requestAnimationFrame(loop)};$('pause').onclick=()=>{playing=false;cancelAnimationFrame(raf)};$('reset').onclick=()=>{playing=false;cancelAnimationFrame(raf);draw(0)}
function loop(now){if(!playing)return;const t=((now-start)/1000)%duration;draw(t);raf=requestAnimationFrame(loop)}
$('render').onclick=()=>{if(!chars.length){$('msg').textContent='Add characters first.';return}const fps=30,m=MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm',r=new MediaRecorder(c.captureStream(fps),{mimeType:m,videoBitsPerSecond:16000000}),chunks=[];r.ondataavailable=e=>e.data.size&&chunks.push(e.data);r.onstop=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(chunks,{type:'video/webm'}));a.download='character-size-comparison.webm';a.click();$('msg').textContent='Comparison video rendered — WebM download started.'};r.start();$('msg').textContent='Rendering…';const z=performance.now();function q(now){const t=(now-z)/1000;if(t>=duration){draw(duration-.001);r.stop();return}draw(t);requestAnimationFrame(q)}requestAnimationFrame(q)}
fit();update();render();