const $=id=>document.getElementById(id),c=$('c'),x=c.getContext('2d');let imgs=[],scenes=[],playing=false,raf=0,start=0;const state={duration:8};
function fitCanvas(){const [a,b]=$('ratio').value.split(':').map(Number);c.width=960;c.height=Math.round(960*b/a);draw(0)}
function ease(v){return v<.5?2*v*v:1-Math.pow(-2*v+2,2)/2}
function drawImageContain(img,cx,cy,maxW,maxH,scale=1,alpha=1,blur=0){const s=Math.min(maxW/img.width,maxH/img.height)*scale;x.save();x.globalAlpha=alpha;x.translate(cx,cy);x.filter=(blur?'blur('+blur+'px) ':'')+($('mono').checked?'grayscale(1) contrast(1.12)':'');x.drawImage(img,-img.width*s/2,-img.height*s/2,img.width*s,img.height*s);x.restore()}
function sceneAt(t){let acc=0;for(let i=0;i<scenes.length;i++){const end=acc+scenes[i].duration;if(t<end)return{i,p:(t-acc)/scenes[i].duration};acc=end}return{i:Math.max(0,scenes.length-1),p:1}}
function draw(t){const W=c.width,H=c.height;x.clearRect(0,0,W,H);const bg=x.createRadialGradient(W*.5,H*.46,0,W*.5,H*.46,W*.78);bg.addColorStop(0,'#292a30');bg.addColorStop(.5,'#101116');bg.addColorStop(1,'#020203');x.fillStyle=bg;x.fillRect(0,0,W,H);if(imgs.length){const z=sceneAt(t),k=z.i,p=z.p,e=ease(p),s=scenes[k],cur=imgs[k],prev=k>0?imgs[k-1]:null,dir=k%2?-1:1,baseY=H*.51;if(prev)drawImageContain(prev,W*.5-dir*W*.62*(1-e),baseY,W*.7,H*.9,.7,.18,3);let cx=W*.5,cy=baseY,sc=.78;if($('motion').value==='zigzag'){cx=W*.5+dir*W*.20*Math.sin(e*Math.PI);cy=baseY-H*.025*Math.sin(e*Math.PI);sc=.74+.08*Math.sin(e*Math.PI)}else if($('motion').value==='push'){cx=W*.5-dir*W*.50*(1-e);sc=.70+.12*e}else{cx=W*.5+Math.sin(e*Math.PI*2)*W*.055;cy=baseY+Math.cos(e*Math.PI*2)*H*.018}drawImageContain(cur,cx,cy,W*.78,H*.9,sc,1,0);if(k<scenes.length-1&&p>.72)drawImageContain(imgs[k+1],W*.5+dir*W*.42*(1-(p-.72)/.28),baseY,W*.72,H*.86,.72,.5,1);x.fillStyle='#fff';x.font='800 '+Math.max(18,W*.026)+'px system-ui';x.fillText(s.title||'',W*.08,H*.82);x.fillStyle='#a8a8b0';x.font='500 '+Math.max(10,W*.012)+'px system-ui';x.fillText(s.sub||'',W*.08,H*.87)}x.strokeStyle='rgba(232,255,67,.72)';x.lineWidth=Math.max(1,W/900);x.beginPath();x.moveTo(W*.06,H*.77);x.bezierCurveTo(W*.30,H*.68,W*.60,H*.87,W*.94,H*.25);x.stroke()}
function updateTime(t){$('time').textContent='00:'+String(Math.floor(t)).padStart(2,'0')+' / '+fmt(state.duration)}
function fmt(v){const m=Math.floor(v/60),s=Math.floor(v%60);return String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
function renderTimeline(){const box=$('timeline');box.innerHTML='';if(!scenes.length){box.innerHTML='<div class="empty">Upload characters to build the timeline.</div>';return}scenes.forEach((s,i)=>{const d=document.createElement('div');d.className='scene';d.innerHTML='<div class="sceneTop"><span class="sceneNum">'+String(i+1).padStart(2,'0')+'</span><img src="'+s.img.src+'"><div style="flex:1"><b style="font-size:10px">Scene '+(i+1)+'</b><div style="font-size:9px;color:#686972">'+s.duration.toFixed(1)+' sec</div></div></div><div class="sceneFields"><input data-i="'+i+'" data-k="title" value="'+esc(s.title)+'" placeholder="Character name"><input data-i="'+i+'" data-k="sub" value="'+esc(s.sub)+'" placeholder="Achievement"><input data-i="'+i+'" data-k="duration" type="number" min=".5" max="10" step=".1" value="'+s.duration+'"><select data-i="'+i+'" data-k="align"><option value="left" '+(s.align==='left'?'selected':'')+'>left</option><option value="center" '+(s.align==='center'?'selected':'')+'>center</option><option value="right" '+(s.align==='right'?'selected':'')+'>right</option></select></div>';box.appendChild(d)});box.querySelectorAll('[data-i]').forEach(el=>el.oninput=()=>{const i=+el.dataset.i,k=el.dataset.k;scenes[i][k]=k==='duration'?Math.max(.5,Math.min(10,+el.value||1)):el.value;state.duration=scenes.reduce((a,s)=>a+s.duration,0);$('duration').value=state.duration.toFixed(1);draw(0);updateTime(0);renderTimeline()})}
function esc(v){return String(v).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function loadFiles(list){const files=[...list].filter(f=>f.type.startsWith('image/'));const remaining=20-scenes.length;if(remaining<=0){$('msg').textContent='Maximum 20 characters reached.';return}files.slice(0,remaining).forEach(f=>{const i=new Image;i.onload=()=>{imgs.push(i);const base=state.duration/Math.max(1,scenes.length+1);scenes.push({img:i,title:'CHARACTER '+String(scenes.length+1).padStart(2,'0'),sub:'ACHIEVEMENT • 2026',duration:Math.max(.5,base),align:'left'});state.duration=scenes.reduce((a,s)=>a+s.duration,0);$('duration').value=state.duration.toFixed(1);const t=document.createElement('img');t.src=i.src;t.className='thumb';$('thumbs').appendChild(t);renderTimeline();draw(0);$('msg').textContent=scenes.length+' characters loaded.'}};i.src=URL.createObjectURL(f)})}
$('files').onchange=e=>{loadFiles(e.target.files);e.target.value=''};const drop=$('drop');['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>loadFiles(e.dataTransfer.files));
$('ratio').onchange=fitCanvas;$('duration').oninput=()=>{const next=Math.max(2,Math.min(30,+$('duration').value||8));const old=scenes.reduce((a,s)=>a+s.duration,0)||1;state.duration=next;$('duration').value=next;const scale=next/old;scenes.forEach(s=>s.duration*=scale);renderTimeline();draw(0);updateTime(0)};
$('preview').onclick=()=>{playing=!playing;if(playing){start=performance.now();$('preview').textContent='■ Stop Preview';raf=requestAnimationFrame(loop)}else{$('preview').textContent='▶ Preview';cancelAnimationFrame(raf)}};function loop(now){if(!playing)return;const t=((now-start)/1000)%state.duration;draw(t);updateTime(t);raf=requestAnimationFrame(loop)}
$('render').onclick=()=>{if(!imgs.length){$('msg').textContent='Add at least one character image first.';return}if(playing){playing=false;cancelAnimationFrame(raf);$('preview').textContent='▶ Preview'}const d=state.duration,f=+$('fps').value,m=MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm',r=new MediaRecorder(c.captureStream(f),{mimeType:m,videoBitsPerSecond:16000000}),chunks=[];r.ondataavailable=e=>e.data.size&&chunks.push(e.data);r.onstop=()=>{const blob=new Blob(chunks,{type:'video/webm'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='character-effect-studio.webm';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);$('msg').textContent='Render complete — WebM download started.'};r.start();$('msg').textContent='Rendering scene timeline…';const z=performance.now();function q(now){const t=(now-z)/1000;if(t>=d){draw(d-.001);r.stop();return}draw(t);updateTime(t);requestAnimationFrame(q)}requestAnimationFrame(q)};
fitCanvas();updateTime(0);draw(0);